name: Build Images

on:
  workflow_dispatch:
    inputs:
      game_server_image:
        description: 'Build game server image'
        required: true
        type: boolean
      login_server_image:
        description: 'Build login server image'
        required: true
        type: boolean
      resources_server_image:
        description: 'Build resources server image'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 20
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build game server image
        if:  ${{ inputs.game_server_image }}
        run: |
          mvn package jib:build --no-transfer-progress --pl game-server -am

      - name: Build login server image
        if:  ${{ inputs.login_server_image }}
        run: |
          mvn package jib:build --no-transfer-progress --pl login-server -am

      - name: Build resources server image
        if:  ${{ inputs.resources_server_image }}
        run: |
          mvn package jib:build --no-transfer-progress --pl resources-server -am
